version: '2'

services:

  todo-manager-backend:
    image: todo-manager-backend
    ports:
      - 9000:9000
    environment:
      - TM_CONFIG_MONGODB_URI=mongodb://user:password1@ds259742.mlab.com:59742/todo-manager-db
      - TM_CONFIG_MONGODB_DATABASE_NAME=todo-manager-db
